### ISSUE TITLE
Gem load error (Ruby 2.6.7) on M1 Mac

### ISSUE THREAD

**Issue by danhd123** [envkey/envkey-ruby#9]
When using `gem envkey` (resolving to 1.3.0) in my Gemfile, I get a Gem Load Error trying to run `rails server` (Rails 5.2.6, Ruby 2.6.7):

The envkey-specific logs are:

```
/Users/.../.rbenv/versions/2.6.7/lib/ruby/2.6.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'envkey'. (Bundler::GemRequireError)
Gem Load Error is: As of 1.3.0, envkey-ruby only supports 64-bit systems. Please use an earlier version for 32-bit support.
Backtrace for gem load error is:
/Users/.../.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/envkey-1.3.0/lib/envkey/platform.rb:45:in `arch_part'
/Users/.../.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/envkey-1.3.0/lib/envkey/platform.rb:58:in `lib_file_dir'
/Users/.../.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/envkey-1.3.0/lib/envkey/platform.rb:54:in `fetch_env_path'
/Users/.../.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/envkey-1.3.0/lib/envkey/fetch.rb:6:in `fetch_env'
/Users/.../.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/envkey-1.3.0/lib/envkey/core.rb:30:in `load_env'
/Users/.../.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/envkey-1.3.0/lib/envkey.rb:4:in `<main>'
```

This appears to be because `RbConfig::CONFIG['host_cpu']` is returning `"aarch64"` in this configuration, which is not matched in `platform.rb:24`. Changing that line to `  when /^arm|^aarch/` fixes the issue.

**Comment by danenania** [comment]
Thanks Dan! Will get this merged today.

**Comment by danenania** [comment]
Live in 1.3.1

**Comment by danhd123** [comment]
Thanks, Dane!
